import Head from 'next/head'
import {Sidebar, sidebarValue} from '../components/sidebar'
// import Navbar from '../components/navbar'
import VideoCard from '../components/videocard'
import { sidebar } from '../lib/constant'
import { useEffect, useState } from 'react'
import { fetchSuggestedVideos, fetchSearch } from '../lib/youtubeclone'

export default function Home(  ) {
  const [getVideos, setGetVideos] = useState([])
  const [getMenu, setGetMenu] = useState(null)
  const [sidebarMenu, setSidebarMenu] = useState(sidebar)
  
  useEffect(()=>{
    fetchSearch('gaming')
    .then(data=>setGetVideos(data.items))
  },[])

  useEffect(()=>{
    if(getMenu !== 'myhomepage'){
      fetchSearch(getMenu)
      .then(data=>setGetVideos(data.items))
    } else {
      fetchSearch()
      .then(data=>setGetVideos(data.items))
    }
  },[getMenu])
  
  const handleClickSidebarMenu = (id, menu) => {
    setGetMenu(menu)
    setSidebarMenu(prev=>{
        return prev.map(data=>{
            return data.id === id ? {...data, isFocus : data.isFocus? data.isFocus : !data.isFocus}  : {...data, isFocus : false}
        })
    })
  }
  
  const handleChangeSearch = (event) => {
    setQSearch(event.target.value)
  }

  const handleClickSubmit = (event) => {
    event.preventDefault();
  }

  return (
    <>
      <Head>
        <title>YOUTUBE CLONE</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/icon/yt-icon.png" />
      </Head>
      {/* <Navbar /> */}
      <div className='md:flex md:mx-5'>
        <Sidebar 
        handleClickSidebarMenu={handleClickSidebarMenu}
        sidebarMenu={sidebarMenu} />
        <main className='md:border-l px-5 py-16 md:py-3 '>
        <span className='font-bold text-2xl border-b-4 border-red-600 pb-1'>{getMenu === null ? 'Home' : getMenu}</span>
        <div className='flex flex-col md:flex-none md:grid md:grid-cols-5 md:gap-2 md:max-w-[100rem] md:mx-auto my-5'>
          <VideoCard videos={getVideos} />
        </div>
        </main>
      </div>
    </>
  )
}
