import Head from 'next/head'
import Sidebar from '../components/sidebar'
import Navbar from '../components/navbar'
import VideoCard from '../components/videocard'
import { useEffect, useState } from 'react'
import {sidebar} from '../lib/constant'
import { fetchFromAPI } from '../lib/youtubeclone'

export default function Home( ) {
  const [videos, setVideos] = useState([])
  const [urls] = useState('relatedToVideoId=7ghhRHRP6t4&part=id%2Csnippet&type=video&maxResults=50')

  useEffect(()=>{
    fetchFromAPI(urls)
    .then(data=>setVideos(data.items))
  },[urls])

  console.log(videos)
  return (
    <>
      <Head>
        <title>YOUTUBE CLONE</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/icon/yt-icon.png" />
      </Head>
      <Navbar />
      <Sidebar />
      <main className=''>
        <VideoCard videos={videos} />
      </main>
    </>
  )
}
